### ISSUE TITLE
RemoveNamespace component

### ISSUE THREAD

**Issue by ghost** [BizTalkComponents/ManageMessageNamespace#5]
Problem to use "RemoveNamespace" if a field has a attribute and is empty e.g. "<test3 test="example"/>".
Error code given by the Windows application log is:

Reason: Token StartAttribute in state Element Content would result in an invalid XML document.

[testfileexample.txt](https://github.com/BizTalkComponents/ManageMessageNamespace/files/85964/testfile.txt)

**Comment by riha** [comment]
Can not reproduce error. Works fine with attached test file and empty attribute values.
